name: uboot
on:
  workflow_dispatch:

jobs:
  build:
    name: uboot
    runs-on: ubuntu-24.04
    steps:
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-linux-gnueabi u-boot-tools lzop gnutls-dev lzma-alone python3

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Build HI3516CV6XX
        run: |
          cd u-boot-hi3516cv6xx
          bash build.sh

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          files: |
            u-boot-*/output/*-nor.bin
            u-boot-*/output/*-nand.bin